CREATE DATABASE AUTO_GLASS

USE AUTO_GLASS

CREATE TABLE PROVIDERS (
CODE INT IDENTITY(1,1),
DESCRIPTION			VARCHAR(500),
CNPJ				VARCHAR(20)

PRIMARY KEY (CODE))

CREATE TABLE PRODUCTS (
CODE				INT IDENTITY(1,1),
CODE_PROVIDER		INT,
DESCRIPTION			VARCHAR(500),
SITUATION			BIT,
MANUFACTURE_DATE	DATETIME,
VALIDITY_DATE		DATETIME

PRIMARY KEY (CODE),
FOREIGN KEY (CODE_PROVIDER) REFERENCES PROVIDERS(CODE))

